export const crewSource = [
  { jobTag: 'director', jobName: 'Directors' },
  { jobTag: 'producer', jobName: 'Producers' },
  { jobTag: 'executive producer', jobName: 'Executive Producers' },
  { jobTag: 'screenplay', jobName: 'Screenwriters' },
  { jobTag: 'editor', jobName: 'Editors' },
  { jobTag: 'camera operator', jobName: 'Camera Operators' },
  { jobTag: 'costume design', jobName: 'Costume Designers' },
  { jobTag: 'art direction', jobName: 'Art Directors' },
  { jobTag: 'director of photography', jobName: 'Directors of Photography' },
  { jobTag: 'sound editor', jobName: 'Sound Editors' },
  { jobTag: 'original music composer', jobName: 'Original Music' },
  { jobTag: 'compositors', jobName: 'Compositors' },
  { jobTag: 'casting', jobName: 'Casting' },
  { jobTag: 'makeup artist', jobName: 'Makeup Artists' },
  { jobTag: 'set costumer', jobName: 'Set Costumers' },
  { jobTag: 'set decoration', jobName: 'Set Decoration' },
  { jobTag: 'fight choreographer', jobName: 'Fight Choreographers' },
  { jobTag: 'visual effects', jobName: 'Visual Effects' },
  { jobTag: 'production design', jobName: 'Production Designers' },
];
