export const tmdbGenres = [
  { value: 28, label: 'Action' },
  { value: 12, label: 'Adventure' },
  { value: 16, label: 'Animation' },
  { value: 35, label: 'Comedy' },
  { value: 80, label: 'Crime' },
  { value: 99, label: 'Documentary' },
  { value: 18, label: 'Drama' },
  { value: 10751, label: 'Family' },
  { value: 14, label: 'Fantasy' },
  { value: 36, label: 'History' },
  { value: 27, label: 'Horror' },
  { value: 10402, label: 'Music' },
  { value: 9648, label: 'Mystery' },
  { value: 10749, label: 'Romance' },
  { value: 878, label: 'Science Fiction' },
  { value: 10770, label: 'TV Movie' },
  { value: 53, label: 'Thriller' },
  { value: 10752, label: 'War' },
  { value: 37, label: 'Western' },
];

export const tmdbGenreColors = [
  { color: '#f9f871', genre: 'Action' },
  { color: '#ffBe4d', genre: 'Adventure' },
  { color: '#ff8051', genre: 'Animation' },
  { color: '#f44169', genre: 'Comedy' },
  { color: '#00c6b3', genre: 'Crime' },
  { color: '#0096e2', genre: 'Documentary' },
  { color: '#0053ca', genre: 'Drama' },
  { color: '#ffe8ff', genre: 'Family' },
  { color: '#c2fcf3', genre: 'Fantasy' },
  { color: '#8a6b9a', genre: 'History' },
  { color: '#d24717', genre: 'Horror' },
  { color: '#930100', genre: 'Music' },
  { color: '#e8d5b5', genre: 'Mystery' },
  { color: '#8bafce', genre: 'Romance' },
  { color: '#fffade', genre: 'Science Fiction' },
  { color: '#8bafce', genre: 'TV Movie' },
  { color: '#ffaaff', genre: 'Thriller' },
  { color: '#6e5e00', genre: 'War' },
  { color: '#954f00', genre: 'Western' },
];
